server:
  port: 9010

spring:
  application:
    name: msgateway
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
              predicates:
                -  name: Path
                   args:
                     pattern: "'/services/'+serviceId.toLowerCase()+'/**'"
              filters:
                - name: RewritePath
                  args:
                     regexp: "'/services/' + serviceId.toLowerCase() + '/(?<remaining>.*)'"
                     replacement: "'/${remaining}'"
          httpclient:
            pool:
              max-connections: 1000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
    enabled: true
    healthcheck:
        enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    instance:
      appname: msgateway
      instanceId: msgateway:${spring.application.instance-id:${random.value}}
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10

logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
    root: INFO
